name: "Setup project"
runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v2
    with:
      node-version: 17
      cache: 'yarn'
  - if: runner.os == 'macOS'
    run: brew install wabt
    shell: bash
  - if: runner.os == 'Linux'
    run: |
      curl -L -s https://github.com/WebAssembly/wabt/releases/download/1.0.31/wabt-1.0.31-ubuntu.tar.gz | tar xvz -C /tmp
      sudo mv /tmp/wabt-1.0.31/bin/* /usr/local/bin
      sudo mv /tmp/wabt-1.0.31/include/* /usr/local/include
      sudo mv /tmp/wabt-1.0.31/lib/*.a /usr/local/lib
      sudo mv /tmp/wabt-1.0.31/share/wabt /usr/local/share
    shell: bash
  - if: runner.os == 'Windows'
    run: |
      curl -L -s https://github.com/WebAssembly/wabt/releases/download/1.0.31/wabt-1.0.31-windows.tar.gz | tar xvz -C /tmp
      mv /tmp/wabt-1.0.31 /c/tools/wabt
      cp /c/tools/wabt/bin/* /c/Windows/system32
    shell: bash
  - run: yarnpkg --pure-lockfile
    shell: bash
