name: Build VS Code Extension

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y imagemagick
        shell: bash
      - run: make -C src/web/vscode-extension install-deps package
